### ISSUE TITLE
Support command-line options

### ISSUE THREAD

**Issue by livibetter** [Regaerd/PyClock#4]
Continued from #3.

PyClock has some in-clock options, it might be a good idea to parse options -- and configuration file in future if desired. Using standard `argparse` is enough for the task.

**Comment by bdreager** [comment]
In response to https://github.com/Regaerd/PyClock/pull/3#issuecomment-175990325
The rearrangement was mostly for https://github.com/Regaerd/PyClock/issues/7, but since that's fixed, it's not a high priority.

Also,  I really like the idea of a config file.

**Comment by livibetter** [comment]
#8 is a blocker of this issue.

I will finish this after #8, then see what we can do with a configuration file, discussing format / locations. At that time, we can add `setup.py` for PyPI, and so on. Version 1.0.0 is not far away and PyClock will be displayed on every Unix-like system, totally clockomination.

**Comment by bdreager** [comment]
PyPI would be excellent.

**Comment by livibetter** [comment]
@Regaerd I got a naming question while writing the option descriptions, `--width` and `--height` will be confusing to users. Since I have read enough of PyClock code, I know what the _`width`_ and _`height`_ actually mean.

Segment width? [Character] Point/Dot width (How could point has width)? These ain't going to work. Character base width?

Any ideas?

---

By the way, I want to turn _center display_ on by default, would you agree on this?

**Comment by livibetter** [comment]
Here is a sample of help message:

```
usage: pyclock.py [-h] [-S] [-C] [-c] [-a] [--color {0,1,2,3,4,5,6,7,8,9}]
                  [-W WIDTH] [-H HEIGHT]

A digital clock for the terminal

optional arguments:
  -h, --help            show this help message and exit
  -S, --no-seconds      do not display seconds
  -C, --no-colons       do not display colons
  -c, --center          center clock display
  -a, --auto-scale      turn on auto scale display
  --color {0,1,2,3,4,5,6,7,8,9}
                        color 0-9 (defauilt: 2)
  -W WIDTH, --width WIDTH
                        width (default: 1)
  -H HEIGHT, --height HEIGHT
                        height (default: 1)
```

Anything needs to reword, or?

**Comment by bdreager** [comment]
> --width and --height will be confusing to users

I was just thinking this as well when I was looking over the source. Since they're used to scale segments, might scale width and scale height be better?

> I want to turn center display on by default, would you agree on this?

I'm fine with this.
On that note, any arguments against having autoscale on by default as well?

> Anything needs to reword, or?

That's really nice. I have nothing to add.

**Comment by livibetter** [comment]
> [...] Since they're used to scale segments, might scale width and scale height be better?

They are much better terms, I will use them.

>  On that note, any arguments against having autoscale on by default as well?

I forgot that, I will turn it on by default as well.

**Comment by livibetter** [comment]
Closing this, this was done by #9.
